name: Go Build & Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Install Dependencies
        run: go mod tidy

      - name: Build Project
        run: go build -v ./...

      - name: Test Without AWS (Local Mode)
        run: |
          echo "[INFO] Running in local mode (no AWS)..."
          go run main.go

      - name: Test With AWS (If Credentials Exist)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        shell: bash
        run: |
          if [ -n "$AWS_ACCESS_KEY_ID" ]; then
            echo "[INFO] Running with AWS integration..."
            go run main.go
          else
            echo "[WARNING] No AWS credentials found. Skipping AWS test."
          fi

