name: Go Build & Test Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Install Dependencies
        run: go mod tidy

      - name: Build Project
        run: go build -v ./...

      - name: Run Tests (if any)
        run: go test -v ./...
